language: node_js
node_js:
  - 12.14.0
services:
  - docker

jobs:
  include:
    - name: "MacOS build"
      os: osx
      script: travis_wait 60 scripts/ci.bash

git:
  depth: 3

deploy:
  - provider: releases
    file_glob: true
    draft: true
    tag_name: "$TRAVIS_TAG"
    target_commitish: "$TRAVIS_COMMIT"
    name: "$TRAVIS_TAG"
    skip_cleanup: true
    api_key: f5abd711c9e014865be5f49ff7158e16235b7c35
    file: out/*
    on:
      repo: lab4quant/code-server
      tags: true

cache:
  timeout: 1000
  yarn: true
  directories:
    - source
